### ISSUE TITLE
Expected id member not found.\r\nParameter name: instance

### ISSUE THREAD

**Issue by Hantse** [Azure/azure-mobile-apps-net-client#135]
Hello,

I launch TodoItem sample with Offline Sync, and i've got this error :

"Expected id member not found.\r\nParameter name: instance"

   at Microsoft.WindowsAzure.MobileServices.MobileServiceSerializer.GetId(JObject instance, Boolean ignoreCase, Boolean allowDefault)
   at Microsoft.WindowsAzure.MobileServices.Sync.MobileServiceSyncTable.EnsureIdIsString(JObject instance)
   at Microsoft.WindowsAzure.MobileServices.Sync.MobileServiceSyncTable.<UpdateAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at IMCFollowing.Services.ProfilService.<Update>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at IMCFollowing.ViewModels.ProfilValueDetailViewModel.<UpdateProfil>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at IMCFollowing.ViewModels.UserValueCollectionViewModel.<AddItem>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at IMCFollowing.ViewModels.UserValueCollectionViewModel.<RefreshItemsAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at IMCFollowing.UC.Stats.<Stats_Loaded>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Threading.WinRTSynchronizationContext.Invoker.InvokeCore()

**Comment by lindydonna** [comment]
The repo issues are for bug reports, so I'm closing this issue. 

For questions, please post on StackOverflow with the tag azure-mobile-services or MSDN forums: https://social.msdn.microsoft.com/forums/azure/en-US/home?forum=azuremobile.

To help track down the issue, please follow the steps here: https://github.com/Azure/azure-mobile-apps/wiki/Help,-my-app-isn't-working!
