### ISSUE TITLE
InvalidOperationException if language is Turkish (tr-TR)

### ISSUE THREAD

**Issue by kinex** [Azure/azure-mobile-apps-net-client#168]
An exception `InvalidOperationException` is thrown if the current language is Turkish (tr-TR). Additional information: No 'id' member found on type `MyDataObject`

I guess this is related to invalid use of string comparison or string modifications methods. Tested with the latest official release (Windows 10 UWP app). This issue breaks my app for any Turkish users.

Stack trace:
```
   at Microsoft.WindowsAzure.MobileServices.MobileServiceContractResolver.DetermineIdProperty(Type type, IEnumerable`1 properties)
   at Microsoft.WindowsAzure.MobileServices.MobileServiceContractResolver.CreateProperties(Type type, MemberSerialization memberSerialization)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateObjectContract(Type objectType)
   at Microsoft.WindowsAzure.MobileServices.MobileServiceContractResolver.CreateObjectContract(Type type)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract(Type objectType)
   at Microsoft.WindowsAzure.MobileServices.MobileServiceContractResolver.ResolveTableName(Type type)
   at Microsoft.WindowsAzure.MobileServices.MobileServiceClient.GetSyncTable[T]()
```

Possible fix in MobileServiceContractResolver.DetermineIdProperty:
`JsonProperty[] idProperties = properties.Where(p => idPropertyNames.Contains(p.PropertyName) && !p.Ignored).ToArray();`
=>
`JsonProperty[] idProperties = properties.Where(p => idPropertyNames.Contains(p.PropertyName, StringComparison.OrdinalIgnoreCase) && !p.Ignored).ToArray();`

In addition I would check all uses of `Contains` (or preferably all string comparisons / modifications).

**Comment by elamalani** [comment]
Hi there, thank you for using Azure Mobile Apps. Please look at this section of the ReadMe that highlights the [future of Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps-net-client#future-of-azure-mobile-apps). Looks like this issue was opened long back, I'm closing this for now but feel free to reach out in case you have any questions. Thanks!
