### ISSUE TITLE
SQLiteException in Xamarin.Forms Droid App API Level 15

### ISSUE THREAD

**Issue by ericbrunner** [Azure/azure-mobile-apps-net-client#227]
Hello,

I use Microsoft.Azure.Mobile.Client.SQLiteStore v 2.1.1 with SQLLitePCL v.3.8.7.2 in my Xamarin.Forms Android App.

On Android devices with API Level >= 16 all works well. But I have one device which has API Level 15 and there I get that exception.  

Any idea?
thanks
Eric

Xamarin caused by: android.runtime.JavaProxyThrowable: SQLitePCL.SQLiteException: Unable to prepare the sql statement: INSERT OR IGNORE INTO [TodoItem] ([id]) VALUES (@p0),(@p1),(@p2),(@p3),(@p4),(@p5),(@p6),(@p7),(@p8),(@p9),(@p10),(@p11),(@p12) Details: near ",": syntax error
  at SQLitePCL.SQLiteConnection.Prepare (System.String sql) [0x00062] in <e8b16f22c5de44f285e90948d6ee67ee>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <fe5ae17f49cd42d9923d7a78735dd424>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0004e] in <fe5ae17f49cd42d9923d7a78735dd424>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in <fe5ae17f49cd42d9923d7a78735dd424>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in <fe5ae17f49cd42d9923d7a78735dd424>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <fe5ae17f49cd42d9923d7a78735dd424>:0 
  at Microsoft.WindowsAzure.MobileServices.Sync.PullAction+<ProcessAll>d__15.MoveNext () [0x00189] in <a35539c18af6417aa736151c4bcf2fb3>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <fe5ae17f49cd42d9923d7a78735dd424>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0004e] in <fe5ae17f49cd42d9923d7a78735dd424>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in <fe5ae17f49cd42d9923d7a78735dd424>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in <fe5ae17f49cd42d9923d7a78735dd424>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <fe5ae17f49cd42d9923d7a78735dd424>:0 
  at Microsoft.WindowsAzure.MobileServices.Sync.PullAction+<ProcessTableAsync>d__14.MoveNext () [0x001d9] in <a35539c18af6417aa736151c4bcf2fb3>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <fe5ae17f49cd42d9923d7a78735dd424>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0004e] in <fe5ae17f49cd42d9923d7a78735dd424>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in <fe5ae17f49cd42d9923d7a78735dd424>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in <fe5ae17f49cd42d9923d7a78735dd424>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <fe5ae17f49cd42d9923d7a78735dd424>:0 
  at Microsoft.WindowsAzure.MobileServices.Sync.TableAction+<ExecuteAsync>d__29.MoveNext () [0x002a5] in <a35539c18af6417aa736151c4bcf2fb3>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <fe5ae17f49cd42d9923d7a78735dd424>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0004e] in <fe5ae17f49cd42d9923d7a78735dd424>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in <fe5ae17f49cd42d9923d7a78735dd424>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in <fe5ae17f49cd42d9923d7a78735dd424>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <fe5ae17f49cd42d9923d7a78735dd424>:0 
  at Microsoft.WindowsAzure.MobileServices.Sync.MobileServiceSyncContext+<ExecuteSyncAction>d__34.MoveNext () [0x0008e] in <a35539c18af6417aa736151c4bcf2fb3>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <fe5ae17f49cd42d9923d7a78735dd424>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0004e] in <fe5ae17f49cd42d9923d7a78735dd424>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in <fe5ae17f49cd42d9923d7a78735dd424>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in <fe5ae17f49cd42d9923d7a78735dd424>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <fe5ae17f49cd42d9923d7a78735dd424>:0 
  at Microsoft.WindowsAzure.MobileServices.Sync.MobileServiceSyncContext+<PullAsync>d__30.MoveNext () [0x0039b] in <a35539c18af6417aa736151c4bcf2fb3>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <fe5ae17f49cd42d9923d7a78735dd424>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0004e] in <fe5ae17f49cd42d9923d7a78735dd424>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in <fe5ae17f49cd42d9923d7a78735dd424>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in <fe5ae17f49cd42d9923d7a78735dd424>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <fe5ae17f49cd42d9923d7a78735dd424>:0 
  at mobile_rolsped.TodoItemManager+<SyncAsync>d__15.MoveNext () [0x0013e] in <45638649a56d4d96bf47435f7f18ae5a>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <fe5ae17f49cd42d9923d7a78735dd424>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0004e] in <fe5ae17f49cd42d9923d7a78735dd424>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in <fe5ae17f49cd42d9923d7a78735dd424>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in <fe5ae17f49cd42d9923d7a78735dd424>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <fe5ae17f49cd42d9923d7a78735dd424>:0 
  at mobile_rolsped.TodoList+<RefreshItems>d__13.MoveNext () [0x000dd] in <45638649a56d4d96bf47435f7f18ae5a>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <fe5ae17f49cd42d9923d7a78735dd424>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0004e] in <fe5ae17f49cd42d9923d7a78735dd424>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in <fe5ae17f49cd42d9923d7a78735dd424>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in <fe5ae17f49cd42d9923d7a78735dd424>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <fe5ae17f49cd42d9923d7a78735dd424>:0 
  at mobile_rolsped.TodoList+<loginButton_Clicked>d__4.MoveNext () [0x0018a] in <45638649a56d4d96bf47435f7f18ae5a>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <fe5ae17f49cd42d9923d7a78735dd424>:0 
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>m__0 (System.Object state) [0x00000] in <fe5ae17f49cd42d9923d7a78735dd424>:0 
  at Android.App.SyncContext+<Post>c__AnonStorey0.<>m__0 () [0x00000] in <79e6945a2f4a4e2f844e36c860dfb012>:0 
  at Java.Lang.Thread+RunnableImplementor.Run () [0x0000b] in <79e6945a2f4a4e2f844e36c860dfb012>:0 
  at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in <79e6945a2f4a4e2f844e36c860dfb012>:0 
  at (wrapper dynamic-method) System.Object:c787935d-23d8-4aea-ad13-d81cc17112a8 (intptr,intptr)
	at mono.java.lang.RunnableImplementor.n_run(Native Method)
	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
	at android.os.Handler.handleCallback(Handler.java:605)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:4476)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:816)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:583)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by dhei** [comment]
Hello @ericbrunner,

We support Android API level 19-24, unfortunately API level 15 is not supported. Specifically, v2.1.1 Microsoft.Azure.Mobile.Client.SQLiteStore works with Android API level 19-23. Use the latest v3.0.1 Microsoft.Azure.Mobile.Client.SQLiteStore for Android API level 24. Hope this clarifies a little bit.

**Comment by jamesmontemagno** [comment]
@dhei 

Do we have this documented somewhere? On my libraries I add somethign like this:

**Platform Support**

|Platform|Supported|Version|
| ------------------- | :-----------: | :------------------: |
|Xamarin.iOS|Yes|iOS 7+|
|Xamarin.iOS Unified|Yes|iOS 7+|
|Xamarin.Android|Yes|API 14+|
|Windows Phone Silverlight|Yes|8.0+|
|Windows Phone RT|---|8.1+|
|Windows Store RT|---|8.1+|
|Windows 10 UWP|---|10+|
|Xamarin.Mac|No||

**Comment by dhei** [comment]
@jamesmontemagno Thanks for pointing this out, I was actually talking with @adrianhall on this recently. We will definitely add such info to our documentation.

**Comment by ericbrunner** [comment]
hello @dhei,

Thanks for your clarification. So I am forced to put my app to minimum API Level 19 to work properly?! 

thanks

**Comment by jamesmontemagno** [comment]
@ericbrunner that is the minimum they support, but if you tested your app just fine on 16 then it could be fine actually. Droping 15 alone isn't much: https://developer.android.com/about/dashboards/index.html

**Comment by jamesmontemagno** [comment]
@ericbrunner, however if you update to 3.0 (make sure to read the readme files as there are a few differences in setup: https://github.com/jamesmontemagno/app-coffeecups/blob/master/CoffeeCups.Shared/Services/AzureService.cs#L59-L78 then that uses SQLite.raw, which has a bundled version of SQLite and that should work on farther back devices.

**Comment by ericbrunner** [comment]
@jamesmontemagno

We have enterprise apps. Therefore we dont publish them in playstore. I will further test them on devices between 16-19 and if no error occurs then I will take your helpful advice. thanks again

**Comment by adrianhall** [comment]
I've just finished adding support information to the HOWTO documentation on azure.com documentation.  We need to add it to the README in each REPO as well.  That will have a separate issue.

Is there anything else to be done for this issue or can we close it?

**Comment by ericbrunner** [comment]
@adrianhall you can close it

**Comment by ericbrunner** [comment]
@dhei 
I just updated to v. 3.0.1 and get that. Any idea?

10-03 12:27:21.181 D/Mono    (26453): Assembly Ref addref Microsoft.WindowsAzure.Mobile.SQLiteStore[0x5aec1fa0] -> System.Runtime.Extensions[0x5af51e68]: 5
10-03 12:27:21.191 D/Mono    (26453): Assembly Ref addref Microsoft.WindowsAzure.Mobile.SQLiteStore[0x5aec1fa0] -> SQLitePCLRaw.batteries_green[0x5aed27f8]: 2
10-03 12:27:21.191 D/Mono    (26453): Assembly Ref addref SQLitePCLRaw.batteries_green[0x5aed27f8] -> SQLitePCLRaw.provider.e_sqlite3[0x5aed5060]: 2
10-03 12:27:21.191 D/Mono    (26453): Assembly Ref addref SQLitePCLRaw.provider.e_sqlite3[0x5aed5060] -> SQLitePCLRaw.core[0x5aed3530]: 3
10-03 12:27:21.201 D/Mono    (26453): Assembly Ref addref SQLitePCLRaw.batteries_green[0x5aed27f8] -> SQLitePCLRaw.core[0x5aed3530]: 4
10-03 12:27:21.211 D/Mono    (26453): DllImport attempting to load: 'e_sqlite3'.
10-03 12:27:21.211 D/Mono    (26453): DllImport error loading library './libe_sqlite3': 'Cannot load library: load_library[1093]: Library '/data/data/com.xamarin.sample.mobile_rolsped/lib/./libe_sqlite3' not found'.
10-03 12:27:21.221 D/Mono    (26453): DllImport loaded library './libe_sqlite3.so'.
10-03 12:27:21.221 D/Mono    (26453): DllImport searching in: 'e_sqlite3' ('./libe_sqlite3.so').
10-03 12:27:21.221 D/Mono    (26453): Searching for 'sqlite3_libversion_number'.
10-03 12:27:21.221 D/Mono    (26453): Probing 'sqlite3_libversion_number'.
10-03 12:27:21.221 D/Mono    (26453): Found as 'sqlite3_libversion_number'.
10-03 12:27:21.231 D/Mono    (26453): DllImport searching in: 'e_sqlite3' ('./libe_sqlite3.so').
10-03 12:27:21.231 D/Mono    (26453): Searching for 'sqlite3_open'.
10-03 12:27:21.231 D/Mono    (26453): Probing 'sqlite3_open'.
10-03 12:27:21.231 D/Mono    (26453): Found as 'sqlite3_open'.
10-03 12:27:21.241 D/Mono    (26453): DllImport searching in: 'e_sqlite3' ('./libe_sqlite3.so').
10-03 12:27:21.241 D/Mono    (26453): Searching for 'sqlite3_close'.
10-03 12:27:21.241 D/Mono    (26453): Probing 'sqlite3_close'.
10-03 12:27:21.241 D/Mono    (26453): Found as 'sqlite3_close'.
10-03 12:27:21.281 D/Mono    (26453): DllImport searching in: 'e_sqlite3' ('./libe_sqlite3.so').
10-03 12:27:21.281 D/Mono    (26453): Searching for 'sqlite3_errmsg'.
10-03 12:27:21.281 D/Mono    (26453): Probing 'sqlite3_errmsg'.
10-03 12:27:21.281 D/Mono    (26453): Found as 'sqlite3_errmsg'.
Unhandled Exception:

System.TypeInitializationException: The type initializer for 'mobile_rolsped.TodoItemManager' threw an exception.

**Comment by adrianhall** [comment]
what does the new SQLiteStore() call look like?

**Comment by jamesmontemagno** [comment]
@adrianhall Well it looks like the azure mobile apps calls Batteries.Init() so we probably don't need to call it in our code, which is a win...

The SQLiteStore() constructor is the same... but you need to specify and actually create a file for Android, which seems absolutely incorrect and the library should do it for you as this is a breaking change for sure and hard for developers to use... see my blog: http://motzcod.es/post/150988588867/updating-azure-mobile-sqlitestore-to-30
