### ISSUE TITLE
push.RegisterAsync(registrationId) returns 400 error

### ISSUE THREAD

**Issue by mikejohanson** [Azure/azure-mobile-apps-net-client#280]
Hi,

I've updated my node backend to v4.0.1 and I'm getting the following error on both native iOS and Xamarin.Droid:
```
2017-01-19T03:53:20.061Z - error:  Error: 400 - Installation validation failed with following error(s):
An invalid tag(s) ',_UserId:Custom:XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX' was supplied. Valid tag characters are alphanumeric, _, @, -, ., : and #..TrackingId:54003b80-13d0-467f-8a1d-b1e3aa51c5c3_G7,TimeStamp:1/19/2017 3:53:21 AM
    at Function.ServiceClient._normalizeError (/Users/mike/Documents/Development/Azure/node_modules/azure-common/lib/services/serviceclient.js:814:23)
    at NotificationHubService.ServiceClient._processResponse (/Users/mike/Documents/Development/Azure/node_modules/azure-common/lib/services/serviceclient.js:455:41)
    at Request.ServiceClient._performRequest.self._buildRequestOptions.processResponseCallback [as _callback] (/Users/mike/Documents/Development/Azure/node_modules/azure-common/lib/services/serviceclient.js:213:35)
    at Request.init.self.callback (/Users/mike/Documents/Development/Azure/node_modules/azure-common/node_modules/request/request.js:187:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/Users/mike/Documents/Development/Azure/node_modules/azure-common/node_modules/request/request.js:1044:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/Users/mike/Documents/Development/Azure/node_modules/azure-common/node_modules/request/request.js:965:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:478:9)
    at process._tickCallback (node.js:392:17)

```
Seems like a similar error as Azure/azure-mobile-apps-node#508, However I am running the server locally for development. 

Ref https://github.com/Azure/azure-mobile-apps-node/issues/507#issuecomment-273400273 

Thanks,
Mike

**Comment by adrianhall** [comment]
Can you post your registration code?   Also, how is the APp Service Push configured?

(Also note that the servers are no longer consistent with App Service Push, so we are out of sync right now.)

**Comment by mikejohanson** [comment]
I don't have App Service Push configured. Push is configured via the azureMobile.js file with the following:
 ```
notifications: {
    hubName: '',
    connectionString: ''
  }
```

**Comment by adrianhall** [comment]
Thanks for the information.  

The local development case is one we have been discussing for a while now.  I think we need an AlternatePushUrl field, just like the AlternateLoginUrl (and if set, we'll use the AlternateLoginUrl).  This is cross cutting for all the client SDKs. 

In addition, I think we need a stub in the Node and ASP.NET SDKs that accept the Installation and just log it (i.e. don't do anything) so that you can operate completely independently of the net when doing local development.

I think that, between the two, we should be ok.  Does this seem like a reasonable solution to you?

**Comment by mikejohanson** [comment]
I like the idea of being able to operate independently of the net, so with that in mind I think a stub would be nice. 
However, the reason I originally posted this in https://github.com/Azure/azure-mobile-apps-node/issues/507 was to kind of say, as @danderson00 mentioned in https://github.com/Azure/azure-mobile-apps-node/issues/507#issuecomment-265562139, that I do like being able to see my push notifications actually come through when doing local development. But, I suppose it's not the end of the world if they don't actually come through 😃

**Comment by adrianhall** [comment]
That's great Mike - the proposal will accomplish both - a completely offline to show the registration working, then an AlternatePushUrl to be specified when testing locally but you want the real registrations. 

I'll get the additional issues filed this week and then close this one once I've referenced them (since they are needed in every single repo we operate).

**Comment by mikejohanson** [comment]
Awesome thanks!

**Comment by adrianhall** [comment]
Client SDK Bugs:

https://github.com/Azure/azure-mobile-apps-js-client/issues/245
https://github.com/Azure/azure-mobile-apps-ios-client/issues/130
https://github.com/Azure/azure-mobile-apps-android-client/issues/81
https://github.com/Azure/azure-mobile-apps-net-client/issues/283

Server SDK Bugs:

https://github.com/Azure/azure-mobile-apps-net-server/issues/180
https://github.com/Azure/azure-mobile-apps-node/issues/507

Closing this one as it's been superceded by the six issues covered above.
