### ISSUE TITLE
Android: WindowManagerBadTokenException in LoginAsync after browser sends callback URL

### ISSUE THREAD

**Issue by BioTurboNick** [Azure/azure-mobile-apps-net-client#363]
Debug log for this event:
```
07-07 19:59:08.622 I/MonoDroid(25302): UNHANDLED EXCEPTION:
07-07 19:59:08.702 I/MonoDroid(25302): Android.Views.WindowManagerBadTokenException: Unable to add window -- token null is not for an application
07-07 19:59:08.702 I/MonoDroid(25302):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <3fd174ff54b146228c505f23cf75ce71>:0 
07-07 19:59:08.702 I/MonoDroid(25302):   at Java.Interop.JniEnvironment+InstanceMethods.CallVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00069] in <bd30a18775d94dc8b6263aecd1ca9077>:0 
07-07 19:59:08.702 I/MonoDroid(25302):   at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0002a] in <bd30a18775d94dc8b6263aecd1ca9077>:0 
07-07 19:59:08.702 I/MonoDroid(25302):   at Android.App.Dialog.Show () [0x0000a] in <d855bac285f44dda8a0d8510b679b1e2>:0 
07-07 19:59:08.702 I/MonoDroid(25302):   at App1.Droid.MainActivity+<AuthenticateAsync>d__3.MoveNext () [0x00166] in D:\App1\App1\App1.Android\MainActivity.cs:66 
07-07 19:59:08.702 I/MonoDroid(25302): --- End of stack trace from previous location where exception was thrown ---
07-07 19:59:08.702 I/MonoDroid(25302):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <3fd174ff54b146228c505f23cf75ce71>:0 
07-07 19:59:08.702 I/MonoDroid(25302):   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <3fd174ff54b146228c505f23cf75ce71>:0 
07-07 19:59:08.702 I/MonoDroid(25302):   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <3fd174ff54b146228c505f23cf75ce71>:0 
07-07 19:59:08.702 I/MonoDroid(25302):   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <3fd174ff54b146228c505f23cf75ce71>:0 
07-07 19:59:08.702 I/MonoDroid(25302):   at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <3fd174ff54b146228c505f23cf75ce71>:0 
07-07 19:59:08.702 I/MonoDroid(25302):   at App1.Services.MobileServiceClientManager+<LoginAsync>d__11.MoveNext () [0x00040] in D:\App1\App1\App1\Services\MobileServiceClientManager.cs:113 
07-07 19:59:08.702 I/MonoDroid(25302): --- End of stack trace from previous location where exception was thrown ---
07-07 19:59:08.702 I/MonoDroid(25302):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <3fd174ff54b146228c505f23cf75ce71>:0 
07-07 19:59:08.702 I/MonoDroid(25302):   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <3fd174ff54b146228c505f23cf75ce71>:0 
07-07 19:59:08.702 I/MonoDroid(25302):   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <3fd174ff54b146228c505f23cf75ce71>:0 
07-07 19:59:08.702 I/MonoDroid(25302):   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <3fd174ff54b146228c505f23cf75ce71>:0 
07-07 19:59:08.702 I/MonoDroid(25302):   at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <3fd174ff54b146228c505f23cf75ce71>:0 
07-07 19:59:08.702 I/MonoDroid(25302):   at App1.ViewModels.ResultsViewModel+<AuthenticateExecuted>d__19.MoveNext () [0x00020] in D:\App1\App1\App1\ViewModels\ResultsViewModel.cs:58 
07-07 19:59:08.702 I/MonoDroid(25302): --- End of stack trace from previous location where exception was thrown ---
07-07 19:59:08.702 I/MonoDroid(25302):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <3fd174ff54b146228c505f23cf75ce71>:0 
07-07 19:59:08.702 I/MonoDroid(25302):   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) [0x00000] in <3fd174ff54b146228c505f23cf75ce71>:0 
07-07 19:59:08.702 I/MonoDroid(25302):   at Android.App.SyncContext+<>c__DisplayClass2_0.<Post>b__0 () [0x00000] in <d855bac285f44dda8a0d8510b679b1e2>:0 
07-07 19:59:08.702 I/MonoDroid(25302):   at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <d855bac285f44dda8a0d8510b679b1e2>:0 
07-07 19:59:08.702 I/MonoDroid(25302):   at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <d855bac285f44dda8a0d8510b679b1e2>:0 
07-07 19:59:08.702 I/MonoDroid(25302):   at (wrapper dynamic-method) System.Object:3e750e04-70ed-447e-a7fc-2d1695a4aa8b (intptr,intptr)
07-07 19:59:08.702 I/MonoDroid(25302):   --- End of managed Android.Views.WindowManagerBadTokenException stack trace ---
07-07 19:59:08.702 I/MonoDroid(25302): android.view.WindowManager$BadTokenException: Unable to add window -- token null is not for an application
07-07 19:59:08.702 I/MonoDroid(25302): 	at android.view.ViewRootImpl.setView(ViewRootImpl.java:898)
07-07 19:59:08.702 I/MonoDroid(25302): 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:337)
07-07 19:59:08.702 I/MonoDroid(25302): 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:109)
07-07 19:59:08.702 I/MonoDroid(25302): 	at android.app.Dialog.show(Dialog.java:505)
07-07 19:59:08.702 I/MonoDroid(25302): 	at mono.java.lang.RunnableImplementor.n_run(Native Method)
07-07 19:59:08.702 I/MonoDroid(25302): 	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
07-07 19:59:08.702 I/MonoDroid(25302): 	at android.os.Handler.handleCallback(Handler.java:739)
07-07 19:59:08.702 I/MonoDroid(25302): 	at android.os.Handler.dispatchMessage(Handler.java:95)
07-07 19:59:08.702 I/MonoDroid(25302): 	at android.os.Looper.loop(Looper.java:148)
07-07 19:59:08.702 I/MonoDroid(25302): 	at android.app.ActivityThread.main(ActivityThread.java:7325)
07-07 19:59:08.702 I/MonoDroid(25302): 	at java.lang.reflect.Method.invoke(Native Method)
07-07 19:59:08.702 I/MonoDroid(25302): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
07-07 19:59:08.702 I/MonoDroid(25302): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by BioTurboNick** [comment]
Nevermind, this is an error in my code!
