### ISSUE TITLE
Refreshing authentication token failed (internal server error)

### ISSUE THREAD

**Issue by kinex** [Azure/azure-mobile-apps-net-client#374]
While testing my app a sync attempt failed and I was forced to login again. My app is using Microsoft/Google OAuth and client SDK 3.1.0. From app service logs I found this:

`2017-08-03T22:44:26,Warning,myapp-svc,a21e85,776373970661688802,0,7744,60,"JWT validation failed: IDX10223: Lifetime validation failed. The token is expired.
ValidTo: '08/03/2017 21:41:03'
Current time: '08/03/2017 22:44:26'..",`
`2017-08-03T22:44:26,Information,myapp-svc,a21e85,776373970661688802,0,7744,60,Sending response: 401.83 Unauthorized,`
`2017-08-03T22:44:26,Verbose,myapp-svc,a21e85,776373970663009886,0,7744,3,Received request: GET https://myapp-svc.azurewebsites.net/.auth/refresh,`
`2017-08-03T22:44:26,Verbose,myapp-svc,a21e85,776373970663009886,0,7744,3,"JWT validation succeeded. Subject: 'sid:<my_sid>', Issuer: 'https://myapp-svc.azurewebsites.net/'.",`
`2017-08-03T22:44:26,Verbose,myapp-svc,a21e85,776373970663009886,0,7744,3,Calling into external HTTP endpoint POST https://login.live.com/oauth20_token.srf.,`
`2017-08-03T22:44:26,Verbose,myapp-svc,a21e85,776373970667990629,0,7744,72,Calling into external HTTP endpoint GET https://apis.live.net/v5.0/me.,`
`2017-08-03T22:44:30,Warning,myapp-svc,a21e85,776373970700234348,0,7744,72,"Call to HTTP endpoint https://apis.live.net/v5.0/me failed: 500 (Internal Server Error). Partial response: {
   ""error"": {
      ""code"": ""server_internal_error"", 
      ""message"": ""An error occurred while retrieving the resource. Try again later.""
   }
}",`
`2017-08-03T22:44:30,Warning,myapp-svc,a21e85,786373970700546855,0,7744,72,"The refresh request for microsoftaccount failed. Details: A new access token was returned, but it could not be exchanged for refreshed user information.",`
`2017-08-03T22:44:30,Information,myapp-svc,a21e85,786373970700546855,0,7744,72,Sending response: 403.81 Forbidden,
`

Later in the log there is same error and it includes also a stack trace:

`2017-08-03T22:52:23,Critical,mycapp-svc,a21e85,776373975433145515,0,7744,97,"System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Azure.AppService.Authentication.MicrosoftAccountProvider.<HandleServerDirectedLoginAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Azure.AppService.Authentication.IdentityProviderBase.<OnCompleteServerDirectedLoginAsync>d__1a.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.AppService.Authentication.IdentityProviderBase.<TryHandleProtocolRequestAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Azure.AppService.Authentication.EasyAuthModule.<OnBeginRequestAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.AppService.Authentication.HttpModuleDispatcher.<DispatchAsync>d__13.MoveNext()",
`

Any ideas what is happening and why?

**Comment by elamalani** [comment]
@kinex Were you able to resolve this issue? It seems to be over 6 months old. I will close it for now but feel free to talk to us in case you have any questions. Thanks!
