### ISSUE TITLE
Offline Mode from within a PCL

### ISSUE THREAD

**Issue by isamllr** [Azure/azure-mobile-apps-net-client#93]
I created a new PCL (.Net 4.5, WP8.1, Win 8.1) where I work with Mobile Apps (everything within the PCL, no interaction with the UI). I'd like to use the **Offline Sync**.
I might be doing sth wrong, but I am unable to initialize the SyncStore (**var store = new MobileServiceSQLiteStore("localstore.db");**)

{SQLitePCL.SQLiteException: Unable to open the database file: localstore.db ---> System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at SQLitePCL.SQLite3Provider.NativeMethods.sqlite3_open_v2(IntPtr filename, IntPtr& db, Int32 flags, IntPtr zVfs)
   at SQLitePCL.SQLite3Provider.SQLitePCL.ISQLite3Provider.Sqlite3Open(IntPtr filename, IntPtr& db, Int32 flags)
   at SQLitePCL.SQLiteConnection..ctor(String fileName, SQLiteOpen openFlag, Boolean setTemporaryDirectory)

Is SQLitePCL incompatible with the Mobile Apps SQLiteStore? Do I need another version?

**Comment by isamllr** [comment]
Got it working, the issue was related to the SQLitePCL for any involved projects --> https://sqlitepcl.codeplex.com/documentation

- Had to install SQLitePCL for the WPF as well, copy the sqlite3.dll to the project marked as "Copy Always".
- Build the WPF for x86 and the PCL for AnyCPU, since SQLitePCL supports x86 for WPF only.
